//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegration.PurchaseOrder_ProductReceipt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PurchaseOrder_ProductReceipt.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PurchaseOrder_ProductReceipt.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PurchaseOrder_ProductReceipt.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PurchaseOrder_ProductReceipt.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PO_ProductReceiptSvcContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class PO_ProductReceiptSvcContract : PortalIntegration.PurchaseOrder_ProductReceipt.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckCreditMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DocumentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InventSiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrigPurchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProcurementCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PurchPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PurchaseLineLineNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ReceiveNowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SumByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string displayOrderingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string employeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymTermIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal quantityOrderedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool updateNowField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckCreditMax {
            get {
                return this.CheckCreditMaxField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckCreditMaxField, value) != true)) {
                    this.CheckCreditMaxField = value;
                    this.RaisePropertyChanged("CheckCreditMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DocumentDate {
            get {
                return this.DocumentDateField;
            }
            set {
                if ((this.DocumentDateField.Equals(value) != true)) {
                    this.DocumentDateField = value;
                    this.RaisePropertyChanged("DocumentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventLocationId {
            get {
                return this.InventLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InventLocationIdField, value) != true)) {
                    this.InventLocationIdField = value;
                    this.RaisePropertyChanged("InventLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InventSiteId {
            get {
                return this.InventSiteIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InventSiteIdField, value) != true)) {
                    this.InventSiteIdField = value;
                    this.RaisePropertyChanged("InventSiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemIdField, value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineAmount {
            get {
                return this.LineAmountField;
            }
            set {
                if ((this.LineAmountField.Equals(value) != true)) {
                    this.LineAmountField = value;
                    this.RaisePropertyChanged("LineAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num {
            get {
                return this.NumField;
            }
            set {
                if ((object.ReferenceEquals(this.NumField, value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrigPurchId {
            get {
                return this.OrigPurchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrigPurchIdField, value) != true)) {
                    this.OrigPurchIdField = value;
                    this.RaisePropertyChanged("OrigPurchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParmId {
            get {
                return this.ParmIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParmIdField, value) != true)) {
                    this.ParmIdField = value;
                    this.RaisePropertyChanged("ParmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentField, value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProcurementCategory {
            get {
                return this.ProcurementCategoryField;
            }
            set {
                if ((this.ProcurementCategoryField.Equals(value) != true)) {
                    this.ProcurementCategoryField = value;
                    this.RaisePropertyChanged("ProcurementCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchId {
            get {
                return this.PurchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchIdField, value) != true)) {
                    this.PurchIdField = value;
                    this.RaisePropertyChanged("PurchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchName {
            get {
                return this.PurchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchNameField, value) != true)) {
                    this.PurchNameField = value;
                    this.RaisePropertyChanged("PurchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchPrice {
            get {
                return this.PurchPriceField;
            }
            set {
                if ((this.PurchPriceField.Equals(value) != true)) {
                    this.PurchPriceField = value;
                    this.RaisePropertyChanged("PurchPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PurchaseLineLineNumber {
            get {
                return this.PurchaseLineLineNumberField;
            }
            set {
                if ((this.PurchaseLineLineNumberField.Equals(value) != true)) {
                    this.PurchaseLineLineNumberField = value;
                    this.RaisePropertyChanged("PurchaseLineLineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ReceiveNow {
            get {
                return this.ReceiveNowField;
            }
            set {
                if ((this.ReceiveNowField.Equals(value) != true)) {
                    this.ReceiveNowField = value;
                    this.RaisePropertyChanged("ReceiveNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecQty {
            get {
                return this.SpecQtyField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecQtyField, value) != true)) {
                    this.SpecQtyField = value;
                    this.RaisePropertyChanged("SpecQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SumBy {
            get {
                return this.SumByField;
            }
            set {
                if ((object.ReferenceEquals(this.SumByField, value) != true)) {
                    this.SumByField = value;
                    this.RaisePropertyChanged("SumBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                if ((this.TransDateField.Equals(value) != true)) {
                    this.TransDateField = value;
                    this.RaisePropertyChanged("TransDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayOrdering {
            get {
                return this.displayOrderingField;
            }
            set {
                if ((object.ReferenceEquals(this.displayOrderingField, value) != true)) {
                    this.displayOrderingField = value;
                    this.RaisePropertyChanged("displayOrdering");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employeeId {
            get {
                return this.employeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.employeeIdField, value) != true)) {
                    this.employeeIdField = value;
                    this.RaisePropertyChanged("employeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymTermId {
            get {
                return this.paymTermIdField;
            }
            set {
                if ((object.ReferenceEquals(this.paymTermIdField, value) != true)) {
                    this.paymTermIdField = value;
                    this.RaisePropertyChanged("paymTermId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal quantityOrdered {
            get {
                return this.quantityOrderedField;
            }
            set {
                if ((this.quantityOrderedField.Equals(value) != true)) {
                    this.quantityOrderedField = value;
                    this.RaisePropertyChanged("quantityOrdered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool updateNow {
            get {
                return this.updateNowField;
            }
            set {
                if ((this.updateNowField.Equals(value) != true)) {
                    this.updateNowField = value;
                    this.RaisePropertyChanged("updateNow");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract))]
    public partial class XppObjectBase : PortalIntegration.PurchaseOrder_ProductReceipt.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class GeneralContract : PortalIntegration.PurchaseOrder_ProductReceipt.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc")]
    public interface PO_ProductReceiptSvc {
        
        // CODEGEN: Generating message contract since message retrieveAll has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveAll", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse retrieveAll(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveAll", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveAllResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse> retrieveAllAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll request);
        
        // CODEGEN: Generating message contract since message retrieveSetting has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveSetting", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveSettingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse retrieveSetting(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveSetting", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveSettingResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse> retrieveSettingAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting request);
        
        // CODEGEN: Generating message contract since message makPurchPackingSlipPost has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/makPurchPackingSlipPost", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/makPurchPackingSlipPostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse makPurchPackingSlipPost(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/makPurchPackingSlipPost", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/makPurchPackingSlipPostResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse> makPurchPackingSlipPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost request);
        
        // CODEGEN: Generating message contract since message retrieveLines has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveLines", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveLinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse retrieveLines(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveLines", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveLinesResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse> retrieveLinesAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines request);
        
        // CODEGEN: Generating message contract since message makPurchReceiptListPost has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/makPurchReceiptListPost", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/makPurchReceiptListPostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse makPurchReceiptListPost(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/makPurchReceiptListPost", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/makPurchReceiptListPostResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse> makPurchReceiptListPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost request);
        
        // CODEGEN: Generating message contract since message retrieveTermsOfpayment has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveTermsOfpayment", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveTermsOfpaymentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PurchaseOrder_ProductReceipt.Fault), Action="http://tempuri.org/PO_ProductReceiptSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse retrieveTermsOfpayment(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PO_ProductReceiptSvc/retrieveTermsOfpayment", ReplyAction="http://tempuri.org/PO_ProductReceiptSvc/retrieveTermsOfpaymentResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse> retrieveTermsOfpaymentAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAll", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAll {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string PurchId;
        
        public retrieveAll() {
        }
        
        public retrieveAll(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            this.CallContext = CallContext;
            this.PurchId = PurchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAllResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAllResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result;
        
        public retrieveAllResponse() {
        }
        
        public retrieveAllResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveSetting", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveSetting {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string PurchId;
        
        public retrieveSetting() {
        }
        
        public retrieveSetting(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            this.CallContext = CallContext;
            this.PurchId = PurchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveSettingResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveSettingResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result;
        
        public retrieveSettingResponse() {
        }
        
        public retrieveSettingResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makPurchPackingSlipPost", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class makPurchPackingSlipPost {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime _documentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _paymentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _productReceipts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public string _purchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine;
        
        public makPurchPackingSlipPost() {
        }
        
        public makPurchPackingSlipPost(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, System.DateTime _documentDate, string _paymentId, string _productReceipts, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine) {
            this.CallContext = CallContext;
            this._documentDate = _documentDate;
            this._paymentId = _paymentId;
            this._productReceipts = _productReceipts;
            this._purchId = _purchId;
            this._purchParmLine = _purchParmLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makPurchPackingSlipPostResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class makPurchPackingSlipPostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result;
        
        public makPurchPackingSlipPostResponse() {
        }
        
        public makPurchPackingSlipPostResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveLines", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveLines {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string PurchId;
        
        public retrieveLines() {
        }
        
        public retrieveLines(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            this.CallContext = CallContext;
            this.PurchId = PurchId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveLinesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveLinesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result;
        
        public retrieveLinesResponse() {
        }
        
        public retrieveLinesResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makPurchReceiptListPost", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class makPurchReceiptListPost {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _purchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine;
        
        public makPurchReceiptListPost() {
        }
        
        public makPurchReceiptListPost(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine) {
            this.CallContext = CallContext;
            this._purchId = _purchId;
            this._purchParmLine = _purchParmLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="makPurchReceiptListPostResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class makPurchReceiptListPostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result;
        
        public makPurchReceiptListPostResponse() {
        }
        
        public makPurchReceiptListPostResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveTermsOfpayment", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveTermsOfpayment {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext;
        
        public retrieveTermsOfpayment() {
        }
        
        public retrieveTermsOfpayment(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveTermsOfpaymentResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveTermsOfpaymentResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result;
        
        public retrieveTermsOfpaymentResponse() {
        }
        
        public retrieveTermsOfpaymentResponse(PortalIntegration.PurchaseOrder_ProductReceipt.Infolog Infolog, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PO_ProductReceiptSvcChannel : PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PO_ProductReceiptSvcClient : System.ServiceModel.ClientBase<PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc>, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc {
        
        public PO_ProductReceiptSvcClient() {
        }
        
        public PO_ProductReceiptSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PO_ProductReceiptSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PO_ProductReceiptSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PO_ProductReceiptSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveAll(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll request) {
            return base.Channel.retrieveAll(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog retrieveAll(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId, out PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveAll(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveAllAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll request) {
            return base.Channel.retrieveAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAllResponse> retrieveAllAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveAll();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveSetting(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting request) {
            return base.Channel.retrieveSetting(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog retrieveSetting(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId, out PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveSetting(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveSettingAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting request) {
            return base.Channel.retrieveSettingAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSettingResponse> retrieveSettingAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveSetting();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveSettingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.makPurchPackingSlipPost(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost request) {
            return base.Channel.makPurchPackingSlipPost(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog makPurchPackingSlipPost(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, System.DateTime _documentDate, string _paymentId, string _productReceipts, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine, out PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost();
            inValue.CallContext = CallContext;
            inValue._documentDate = _documentDate;
            inValue._paymentId = _paymentId;
            inValue._productReceipts = _productReceipts;
            inValue._purchId = _purchId;
            inValue._purchParmLine = _purchParmLine;
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).makPurchPackingSlipPost(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.makPurchPackingSlipPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost request) {
            return base.Channel.makPurchPackingSlipPostAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPostResponse> makPurchPackingSlipPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, System.DateTime _documentDate, string _paymentId, string _productReceipts, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine) {
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.makPurchPackingSlipPost();
            inValue.CallContext = CallContext;
            inValue._documentDate = _documentDate;
            inValue._paymentId = _paymentId;
            inValue._productReceipts = _productReceipts;
            inValue._purchId = _purchId;
            inValue._purchParmLine = _purchParmLine;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).makPurchPackingSlipPostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveLines(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines request) {
            return base.Channel.retrieveLines(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog retrieveLines(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId, out PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveLines(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveLinesAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines request) {
            return base.Channel.retrieveLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLinesResponse> retrieveLinesAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string PurchId) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveLines();
            inValue.CallContext = CallContext;
            inValue.PurchId = PurchId;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveLinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.makPurchReceiptListPost(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost request) {
            return base.Channel.makPurchReceiptListPost(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog makPurchReceiptListPost(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine, out PortalIntegration.PurchaseOrder_ProductReceipt.GeneralContract result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost();
            inValue.CallContext = CallContext;
            inValue._purchId = _purchId;
            inValue._purchParmLine = _purchParmLine;
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).makPurchReceiptListPost(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.makPurchReceiptListPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost request) {
            return base.Channel.makPurchReceiptListPostAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPostResponse> makPurchReceiptListPostAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, string _purchId, PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] _purchParmLine) {
            PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.makPurchReceiptListPost();
            inValue.CallContext = CallContext;
            inValue._purchId = _purchId;
            inValue._purchParmLine = _purchParmLine;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).makPurchReceiptListPostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveTermsOfpayment(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment request) {
            return base.Channel.retrieveTermsOfpayment(request);
        }
        
        public PortalIntegration.PurchaseOrder_ProductReceipt.Infolog retrieveTermsOfpayment(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext, out PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvcContract[] result) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment();
            inValue.CallContext = CallContext;
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse retVal = ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveTermsOfpayment(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse> PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc.retrieveTermsOfpaymentAsync(PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment request) {
            return base.Channel.retrieveTermsOfpaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpaymentResponse> retrieveTermsOfpaymentAsync(PortalIntegration.PurchaseOrder_ProductReceipt.CallContext CallContext) {
            PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment inValue = new PortalIntegration.PurchaseOrder_ProductReceipt.retrieveTermsOfpayment();
            inValue.CallContext = CallContext;
            return ((PortalIntegration.PurchaseOrder_ProductReceipt.PO_ProductReceiptSvc)(this)).retrieveTermsOfpaymentAsync(inValue);
        }
    }
}
