//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegration.LogisticsLocationSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.LogisticsLocationSvcReference.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.LogisticsLocationSvcReference.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.LogisticsLocationSvcReference.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.LogisticsLocationSvcReference.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogisticsLocationSvcContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class LogisticsLocationSvcContract : PortalIntegration.LogisticsLocationSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrimaryTaxRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PartitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PartyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionId {
            get {
                return this.CountryRegionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionIdField, value) != true)) {
                    this.CountryRegionIdField = value;
                    this.RaisePropertyChanged("CountryRegionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAreaId {
            get {
                return this.DataAreaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAreaIdField, value) != true)) {
                    this.DataAreaIdField = value;
                    this.RaisePropertyChanged("DataAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrimary {
            get {
                return this.IsPrimaryField;
            }
            set {
                if ((this.IsPrimaryField.Equals(value) != true)) {
                    this.IsPrimaryField = value;
                    this.RaisePropertyChanged("IsPrimary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrimaryTaxRegistration {
            get {
                return this.IsPrimaryTaxRegistrationField;
            }
            set {
                if ((this.IsPrimaryTaxRegistrationField.Equals(value) != true)) {
                    this.IsPrimaryTaxRegistrationField = value;
                    this.RaisePropertyChanged("IsPrimaryTaxRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.LogisticsLocationSvcReference.NoYes IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationIdField, value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime {
            get {
                return this.ModifiedDateTimeField;
            }
            set {
                if ((this.ModifiedDateTimeField.Equals(value) != true)) {
                    this.ModifiedDateTimeField = value;
                    this.RaisePropertyChanged("ModifiedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Partition {
            get {
                return this.PartitionField;
            }
            set {
                if ((this.PartitionField.Equals(value) != true)) {
                    this.PartitionField = value;
                    this.RaisePropertyChanged("Partition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Party {
            get {
                return this.PartyField;
            }
            set {
                if ((this.PartyField.Equals(value) != true)) {
                    this.PartyField = value;
                    this.RaisePropertyChanged("Party");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract))]
    public partial class XppObjectBase : PortalIntegration.LogisticsLocationSvcReference.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class GeneralContract : PortalIntegration.LogisticsLocationSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="LogisticsLocationSvcReference.LogisticsLocationSvc")]
    public interface LogisticsLocationSvc {
        
        // CODEGEN: Generating message contract since message findByEmployee has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/findByEmployee", ReplyAction="http://tempuri.org/LogisticsLocationSvc/findByEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.Fault), Action="http://tempuri.org/LogisticsLocationSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse findByEmployee(PortalIntegration.LogisticsLocationSvcReference.findByEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/findByEmployee", ReplyAction="http://tempuri.org/LogisticsLocationSvc/findByEmployeeResponse")]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse> findByEmployeeAsync(PortalIntegration.LogisticsLocationSvcReference.findByEmployee request);
        
        // CODEGEN: Generating message contract since message update has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/update", ReplyAction="http://tempuri.org/LogisticsLocationSvc/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.Fault), Action="http://tempuri.org/LogisticsLocationSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.LogisticsLocationSvcReference.updateResponse update(PortalIntegration.LogisticsLocationSvcReference.update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/update", ReplyAction="http://tempuri.org/LogisticsLocationSvc/updateResponse")]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.updateResponse> updateAsync(PortalIntegration.LogisticsLocationSvcReference.update request);
        
        // CODEGEN: Generating message contract since message create has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/create", ReplyAction="http://tempuri.org/LogisticsLocationSvc/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.Fault), Action="http://tempuri.org/LogisticsLocationSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.LogisticsLocationSvcReference.createResponse create(PortalIntegration.LogisticsLocationSvcReference.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/create", ReplyAction="http://tempuri.org/LogisticsLocationSvc/createResponse")]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.createResponse> createAsync(PortalIntegration.LogisticsLocationSvcReference.create request);
        
        // CODEGEN: Generating message contract since message delete has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/delete", ReplyAction="http://tempuri.org/LogisticsLocationSvc/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.LogisticsLocationSvcReference.Fault), Action="http://tempuri.org/LogisticsLocationSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.LogisticsLocationSvcReference.deleteResponse delete(PortalIntegration.LogisticsLocationSvcReference.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogisticsLocationSvc/delete", ReplyAction="http://tempuri.org/LogisticsLocationSvc/deleteResponse")]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.deleteResponse> deleteAsync(PortalIntegration.LogisticsLocationSvcReference.delete request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByEmployee", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findByEmployee {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _employeeId;
        
        public findByEmployee() {
        }
        
        public findByEmployee(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, string _employeeId) {
            this.CallContext = CallContext;
            this._employeeId = _employeeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByEmployeeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findByEmployeeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract[] result;
        
        public findByEmployeeResponse() {
        }
        
        public findByEmployeeResponse(PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class update {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract;
        
        public update() {
        }
        
        public update(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.GeneralContract result;
        
        public updateResponse() {
        }
        
        public updateResponse(PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog, PortalIntegration.LogisticsLocationSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract;
        
        public create() {
        }
        
        public create(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.GeneralContract result;
        
        public createResponse() {
        }
        
        public createResponse(PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog, PortalIntegration.LogisticsLocationSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long[] _recordsRecId;
        
        public delete() {
        }
        
        public delete(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, long[] _recordsRecId) {
            this.CallContext = CallContext;
            this._recordsRecId = _recordsRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.LogisticsLocationSvcReference.GeneralContract[] result;
        
        public deleteResponse() {
        }
        
        public deleteResponse(PortalIntegration.LogisticsLocationSvcReference.Infolog Infolog, PortalIntegration.LogisticsLocationSvcReference.GeneralContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogisticsLocationSvcChannel : PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogisticsLocationSvcClient : System.ServiceModel.ClientBase<PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc>, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc {
        
        public LogisticsLocationSvcClient() {
        }
        
        public LogisticsLocationSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogisticsLocationSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticsLocationSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticsLocationSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.findByEmployee(PortalIntegration.LogisticsLocationSvcReference.findByEmployee request) {
            return base.Channel.findByEmployee(request);
        }
        
        public PortalIntegration.LogisticsLocationSvcReference.Infolog findByEmployee(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, string _employeeId, out PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract[] result) {
            PortalIntegration.LogisticsLocationSvcReference.findByEmployee inValue = new PortalIntegration.LogisticsLocationSvcReference.findByEmployee();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse retVal = ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).findByEmployee(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse> PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.findByEmployeeAsync(PortalIntegration.LogisticsLocationSvcReference.findByEmployee request) {
            return base.Channel.findByEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.findByEmployeeResponse> findByEmployeeAsync(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, string _employeeId) {
            PortalIntegration.LogisticsLocationSvcReference.findByEmployee inValue = new PortalIntegration.LogisticsLocationSvcReference.findByEmployee();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            return ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).findByEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.LogisticsLocationSvcReference.updateResponse PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.update(PortalIntegration.LogisticsLocationSvcReference.update request) {
            return base.Channel.update(request);
        }
        
        public PortalIntegration.LogisticsLocationSvcReference.Infolog update(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract, out PortalIntegration.LogisticsLocationSvcReference.GeneralContract result) {
            PortalIntegration.LogisticsLocationSvcReference.update inValue = new PortalIntegration.LogisticsLocationSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.LogisticsLocationSvcReference.updateResponse retVal = ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).update(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.updateResponse> PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.updateAsync(PortalIntegration.LogisticsLocationSvcReference.update request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.updateResponse> updateAsync(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract) {
            PortalIntegration.LogisticsLocationSvcReference.update inValue = new PortalIntegration.LogisticsLocationSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.LogisticsLocationSvcReference.createResponse PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.create(PortalIntegration.LogisticsLocationSvcReference.create request) {
            return base.Channel.create(request);
        }
        
        public PortalIntegration.LogisticsLocationSvcReference.Infolog create(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract, out PortalIntegration.LogisticsLocationSvcReference.GeneralContract result) {
            PortalIntegration.LogisticsLocationSvcReference.create inValue = new PortalIntegration.LogisticsLocationSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.LogisticsLocationSvcReference.createResponse retVal = ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).create(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.createResponse> PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.createAsync(PortalIntegration.LogisticsLocationSvcReference.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.createResponse> createAsync(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvcContract contract) {
            PortalIntegration.LogisticsLocationSvcReference.create inValue = new PortalIntegration.LogisticsLocationSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.LogisticsLocationSvcReference.deleteResponse PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.delete(PortalIntegration.LogisticsLocationSvcReference.delete request) {
            return base.Channel.delete(request);
        }
        
        public PortalIntegration.LogisticsLocationSvcReference.Infolog delete(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, long[] _recordsRecId, out PortalIntegration.LogisticsLocationSvcReference.GeneralContract[] result) {
            PortalIntegration.LogisticsLocationSvcReference.delete inValue = new PortalIntegration.LogisticsLocationSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            PortalIntegration.LogisticsLocationSvcReference.deleteResponse retVal = ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).delete(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.deleteResponse> PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc.deleteAsync(PortalIntegration.LogisticsLocationSvcReference.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.LogisticsLocationSvcReference.deleteResponse> deleteAsync(PortalIntegration.LogisticsLocationSvcReference.CallContext CallContext, long[] _recordsRecId) {
            PortalIntegration.LogisticsLocationSvcReference.delete inValue = new PortalIntegration.LogisticsLocationSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            return ((PortalIntegration.LogisticsLocationSvcReference.LogisticsLocationSvc)(this)).deleteAsync(inValue);
        }
    }
}
