<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:tns="http://tempuri.org" elementFormDefault="qualified" targetNamespace="http://tempuri.org" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="https://mcs-payrollf535b0099ffa43fcdevaos.axcloud.dynamics.com/soap/services/ESSCourseSvcGroup?xsd=xsd4" namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application" />
  <xs:element name="retrieveAssigned">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="_person" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="retrieveAssignedResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application" minOccurs="0" name="result" nillable="true" type="q1:ArrayOfESSCourseContract" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="retrieveOpenCourses">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="_person" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="retrieveOpenCoursesResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application" minOccurs="0" name="result" nillable="true" type="q2:ArrayOfESSCourseContract" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="retrieveConfirmCourses">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="_person" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="retrieveConfirmCoursesResponse">
    <xs:complexType>
      <xs:sequence>
        <xs:element xmlns:q3="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application" minOccurs="0" name="result" nillable="true" type="q3:ArrayOfESSCourseContract" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>