//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegration.PREOSNoticePeriodsSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PREOSNoticePeriodsSvcReference.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PREOSNoticePeriodsSvcReference.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PREOSNoticePeriodsSvcContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class PREOSNoticePeriodsSvcContract : PortalIntegration.PREOSNoticePeriodsSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalculationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSType EOSTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EarningCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PREOSNoticePeriodsSvcReference.PREmploymentType EmploymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSIntervalType IntervalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoticePeriodCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PartitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalculationCode {
            get {
                return this.CalculationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CalculationCodeField, value) != true)) {
                    this.CalculationCodeField = value;
                    this.RaisePropertyChanged("CalculationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAreaId {
            get {
                return this.DataAreaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAreaIdField, value) != true)) {
                    this.DataAreaIdField = value;
                    this.RaisePropertyChanged("DataAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSType EOSType {
            get {
                return this.EOSTypeField;
            }
            set {
                if ((this.EOSTypeField.Equals(value) != true)) {
                    this.EOSTypeField = value;
                    this.RaisePropertyChanged("EOSType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EarningCode {
            get {
                return this.EarningCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EarningCodeField, value) != true)) {
                    this.EarningCodeField = value;
                    this.RaisePropertyChanged("EarningCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREmploymentType EmploymentType {
            get {
                return this.EmploymentTypeField;
            }
            set {
                if ((this.EmploymentTypeField.Equals(value) != true)) {
                    this.EmploymentTypeField = value;
                    this.RaisePropertyChanged("EmploymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSIntervalType IntervalType {
            get {
                return this.IntervalTypeField;
            }
            set {
                if ((this.IntervalTypeField.Equals(value) != true)) {
                    this.IntervalTypeField = value;
                    this.RaisePropertyChanged("IntervalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime {
            get {
                return this.ModifiedDateTimeField;
            }
            set {
                if ((this.ModifiedDateTimeField.Equals(value) != true)) {
                    this.ModifiedDateTimeField = value;
                    this.RaisePropertyChanged("ModifiedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoticePeriodCode {
            get {
                return this.NoticePeriodCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NoticePeriodCodeField, value) != true)) {
                    this.NoticePeriodCodeField = value;
                    this.RaisePropertyChanged("NoticePeriodCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Partition {
            get {
                return this.PartitionField;
            }
            set {
                if ((this.PartitionField.Equals(value) != true)) {
                    this.PartitionField = value;
                    this.RaisePropertyChanged("Partition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract))]
    public partial class XppObjectBase : PortalIntegration.PREOSNoticePeriodsSvcReference.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class GeneralContract : PortalIntegration.PREOSNoticePeriodsSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PREOSType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PREOSType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resignation = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Termination = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retirement = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Death = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PREmploymentType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PREmploymentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Permanent = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contract = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Probation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DailyWages = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internee = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trainee = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PREOSIntervalType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PREOSIntervalType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Month = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Days = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc")]
    public interface PREOSNoticePeriodsSvc {
        
        // CODEGEN: Generating message contract since message find has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/find", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.Fault), Action="http://tempuri.org/PREOSNoticePeriodsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse find(PortalIntegration.PREOSNoticePeriodsSvcReference.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/find", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/findResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse> findAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.find request);
        
        // CODEGEN: Generating message contract since message update has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/update", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.Fault), Action="http://tempuri.org/PREOSNoticePeriodsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse update(PortalIntegration.PREOSNoticePeriodsSvcReference.update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/update", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/updateResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse> updateAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.update request);
        
        // CODEGEN: Generating message contract since message retrieveAll has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/retrieveAll", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/retrieveAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.Fault), Action="http://tempuri.org/PREOSNoticePeriodsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse retrieveAll(PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/retrieveAll", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/retrieveAllResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse> retrieveAllAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll request);
        
        // CODEGEN: Generating message contract since message delete has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/delete", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.Fault), Action="http://tempuri.org/PREOSNoticePeriodsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse delete(PortalIntegration.PREOSNoticePeriodsSvcReference.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/delete", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/deleteResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse> deleteAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.delete request);
        
        // CODEGEN: Generating message contract since message create has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/create", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.PREOSNoticePeriodsSvcReference.Fault), Action="http://tempuri.org/PREOSNoticePeriodsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse create(PortalIntegration.PREOSNoticePeriodsSvcReference.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PREOSNoticePeriodsSvc/create", ReplyAction="http://tempuri.org/PREOSNoticePeriodsSvc/createResponse")]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse> createAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.create request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _noticePeriodCode;
        
        public find() {
        }
        
        public find(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, string _noticePeriodCode) {
            this.CallContext = CallContext;
            this._noticePeriodCode = _noticePeriodCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result;
        
        public findResponse() {
        }
        
        public findResponse(PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class update {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract;
        
        public update() {
        }
        
        public update(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public bool result;
        
        public updateResponse() {
        }
        
        public updateResponse(PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog, bool result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAll", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAll {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext;
        
        public retrieveAll() {
        }
        
        public retrieveAll(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAllResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAllResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result;
        
        public retrieveAllResponse() {
        }
        
        public retrieveAllResponse(PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] _contractList;
        
        public delete() {
        }
        
        public delete(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] _contractList) {
            this.CallContext = CallContext;
            this._contractList = _contractList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] result;
        
        public deleteResponse() {
        }
        
        public deleteResponse(PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog, PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract;
        
        public create() {
        }
        
        public create(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long result;
        
        public createResponse() {
        }
        
        public createResponse(PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog Infolog, long result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PREOSNoticePeriodsSvcChannel : PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PREOSNoticePeriodsSvcClient : System.ServiceModel.ClientBase<PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc>, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc {
        
        public PREOSNoticePeriodsSvcClient() {
        }
        
        public PREOSNoticePeriodsSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PREOSNoticePeriodsSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PREOSNoticePeriodsSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PREOSNoticePeriodsSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.find(PortalIntegration.PREOSNoticePeriodsSvcReference.find request) {
            return base.Channel.find(request);
        }
        
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog find(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, string _noticePeriodCode, out PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.find inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._noticePeriodCode = _noticePeriodCode;
            PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse retVal = ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).find(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse> PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.findAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.findResponse> findAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, string _noticePeriodCode) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.find inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._noticePeriodCode = _noticePeriodCode;
            return ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.update(PortalIntegration.PREOSNoticePeriodsSvcReference.update request) {
            return base.Channel.update(request);
        }
        
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog update(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract, out bool result) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.update inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse retVal = ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).update(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse> PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.updateAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.update request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.updateResponse> updateAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.update inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.retrieveAll(PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll request) {
            return base.Channel.retrieveAll(request);
        }
        
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog retrieveAll(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, out PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract[] result) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll();
            inValue.CallContext = CallContext;
            PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse retVal = ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).retrieveAll(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse> PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.retrieveAllAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll request) {
            return base.Channel.retrieveAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAllResponse> retrieveAllAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.retrieveAll();
            inValue.CallContext = CallContext;
            return ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).retrieveAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.delete(PortalIntegration.PREOSNoticePeriodsSvcReference.delete request) {
            return base.Channel.delete(request);
        }
        
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog delete(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] _contractList, out PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] result) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.delete inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._contractList = _contractList;
            PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse retVal = ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).delete(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse> PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.deleteAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.deleteResponse> deleteAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.GeneralContract[] _contractList) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.delete inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._contractList = _contractList;
            return ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.create(PortalIntegration.PREOSNoticePeriodsSvcReference.create request) {
            return base.Channel.create(request);
        }
        
        public PortalIntegration.PREOSNoticePeriodsSvcReference.Infolog create(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract, out long result) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.create inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse retVal = ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).create(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse> PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc.createAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.PREOSNoticePeriodsSvcReference.createResponse> createAsync(PortalIntegration.PREOSNoticePeriodsSvcReference.CallContext CallContext, PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvcContract contract) {
            PortalIntegration.PREOSNoticePeriodsSvcReference.create inValue = new PortalIntegration.PREOSNoticePeriodsSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.PREOSNoticePeriodsSvcReference.PREOSNoticePeriodsSvc)(this)).createAsync(inValue);
        }
    }
}
