//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegration.JmgEmployeeAccuralRequestSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.JmgEmployeeAccuralRequestSvcReference.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.JmgEmployeeAccuralRequestSvcReference.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JmgEmployeeAccuralRequestSvcContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class JmgEmployeeAccuralRequestSvcContract : PortalIntegration.JmgEmployeeAccuralRequestSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PartitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long earningsRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long entitlementRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long periodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime profileDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string profileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType requestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime timeDeductionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgWFStatus wFStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long workerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAreaId {
            get {
                return this.DataAreaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAreaIdField, value) != true)) {
                    this.DataAreaIdField = value;
                    this.RaisePropertyChanged("DataAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime {
            get {
                return this.ModifiedDateTimeField;
            }
            set {
                if ((this.ModifiedDateTimeField.Equals(value) != true)) {
                    this.ModifiedDateTimeField = value;
                    this.RaisePropertyChanged("ModifiedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Partition {
            get {
                return this.PartitionField;
            }
            set {
                if ((this.PartitionField.Equals(value) != true)) {
                    this.PartitionField = value;
                    this.RaisePropertyChanged("Partition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy {
            get {
                return this.RequestedByField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedByField, value) != true)) {
                    this.RequestedByField = value;
                    this.RaisePropertyChanged("RequestedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long earningsRecId {
            get {
                return this.earningsRecIdField;
            }
            set {
                if ((this.earningsRecIdField.Equals(value) != true)) {
                    this.earningsRecIdField = value;
                    this.RaisePropertyChanged("earningsRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long entitlementRecId {
            get {
                return this.entitlementRecIdField;
            }
            set {
                if ((this.entitlementRecIdField.Equals(value) != true)) {
                    this.entitlementRecIdField = value;
                    this.RaisePropertyChanged("entitlementRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long period {
            get {
                return this.periodField;
            }
            set {
                if ((this.periodField.Equals(value) != true)) {
                    this.periodField = value;
                    this.RaisePropertyChanged("period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime profileDate {
            get {
                return this.profileDateField;
            }
            set {
                if ((this.profileDateField.Equals(value) != true)) {
                    this.profileDateField = value;
                    this.RaisePropertyChanged("profileDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string profileId {
            get {
                return this.profileIdField;
            }
            set {
                if ((object.ReferenceEquals(this.profileIdField, value) != true)) {
                    this.profileIdField = value;
                    this.RaisePropertyChanged("profileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType requestType {
            get {
                return this.requestTypeField;
            }
            set {
                if ((this.requestTypeField.Equals(value) != true)) {
                    this.requestTypeField = value;
                    this.RaisePropertyChanged("requestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime timeDeductionDate {
            get {
                return this.timeDeductionDateField;
            }
            set {
                if ((this.timeDeductionDateField.Equals(value) != true)) {
                    this.timeDeductionDateField = value;
                    this.RaisePropertyChanged("timeDeductionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgWFStatus wFStatus {
            get {
                return this.wFStatusField;
            }
            set {
                if ((this.wFStatusField.Equals(value) != true)) {
                    this.wFStatusField = value;
                    this.RaisePropertyChanged("wFStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long worker {
            get {
                return this.workerField;
            }
            set {
                if ((this.workerField.Equals(value) != true)) {
                    this.workerField = value;
                    this.RaisePropertyChanged("worker");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract))]
    public partial class XppObjectBase : PortalIntegration.JmgEmployeeAccuralRequestSvcReference.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class GeneralContract : PortalIntegration.JmgEmployeeAccuralRequestSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JmgAccuralRequestType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum JmgAccuralRequestType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompensatoryLeave = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OffDayAllowance = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeDeductionAdjustment = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JmgWFStatus", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum JmgWFStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSubmitted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submitted = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeRequest = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingCancellation = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Returned = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingApproval = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingComplete = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkflowCompleted = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc")]
    public interface JmgEmployeeAccuralRequestSvc {
        
        // CODEGEN: Generating message contract since message find has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/find", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse find(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/find", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse> findAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find request);
        
        // CODEGEN: Generating message contract since message update has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/update", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse update(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/update", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/updateResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse> updateAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update request);
        
        // CODEGEN: Generating message contract since message retrieveAll has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retrieveAll", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retrieveAllResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse retrieveAll(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retrieveAll", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retrieveAllResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse> retrieveAllAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll request);
        
        // CODEGEN: Generating message contract since message delete has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/delete", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse delete(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/delete", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/deleteResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse> deleteAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete request);
        
        // CODEGEN: Generating message contract since message create has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/create", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse create(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/create", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/createResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse> createAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create request);
        
        // CODEGEN: Generating message contract since message findByEmployee has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findByEmployee", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findByEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse findByEmployee(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findByEmployee", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/findByEmployeeResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse> findByEmployeeAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee request);
        
        // CODEGEN: Generating message contract since message retriveEmployeeRequestioner has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeRequestioner", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeRequestionerRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse retriveEmployeeRequestioner(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeRequestioner", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeRequestionerRespon" +
            "se")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse> retriveEmployeeRequestionerAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner request);
        
        // CODEGEN: Generating message contract since message retriveEmployeeReportees has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeReportees", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeReporteesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Fault), Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse retriveEmployeeReportees(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeReportees", ReplyAction="http://tempuri.org/JmgEmployeeAccuralRequestSvc/retriveEmployeeReporteesResponse")]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse> retriveEmployeeReporteesAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _employeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime _profileDate;
        
        public find() {
        }
        
        public find(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, System.DateTime _profileDate) {
            this.CallContext = CallContext;
            this._employeeId = _employeeId;
            this._profileDate = _profileDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result;
        
        public findResponse() {
        }
        
        public findResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class update {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract;
        
        public update() {
        }
        
        public update(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result;
        
        public updateResponse() {
        }
        
        public updateResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAll", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAll {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        public retrieveAll() {
        }
        
        public retrieveAll(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retrieveAllResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retrieveAllResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result;
        
        public retrieveAllResponse() {
        }
        
        public retrieveAllResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long[] _recordsRecId;
        
        public delete() {
        }
        
        public delete(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, long[] _recordsRecId) {
            this.CallContext = CallContext;
            this._recordsRecId = _recordsRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract[] result;
        
        public deleteResponse() {
        }
        
        public deleteResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract;
        
        public create() {
        }
        
        public create(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result;
        
        public createResponse() {
        }
        
        public createResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByEmployee", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findByEmployee {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _employeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType;
        
        public findByEmployee() {
        }
        
        public findByEmployee(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            this.CallContext = CallContext;
            this._employeeId = _employeeId;
            this._requestType = _requestType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByEmployeeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findByEmployeeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result;
        
        public findByEmployeeResponse() {
        }
        
        public findByEmployeeResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retriveEmployeeRequestioner", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retriveEmployeeRequestioner {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _employeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType;
        
        public retriveEmployeeRequestioner() {
        }
        
        public retriveEmployeeRequestioner(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            this.CallContext = CallContext;
            this._employeeId = _employeeId;
            this._requestType = _requestType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retriveEmployeeRequestionerResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retriveEmployeeRequestionerResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result;
        
        public retriveEmployeeRequestionerResponse() {
        }
        
        public retriveEmployeeRequestionerResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retriveEmployeeReportees", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retriveEmployeeReportees {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _employeeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType;
        
        public retriveEmployeeReportees() {
        }
        
        public retriveEmployeeReportees(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            this.CallContext = CallContext;
            this._employeeId = _employeeId;
            this._requestType = _requestType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retriveEmployeeReporteesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class retriveEmployeeReporteesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result;
        
        public retriveEmployeeReporteesResponse() {
        }
        
        public retriveEmployeeReporteesResponse(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog Infolog, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JmgEmployeeAccuralRequestSvcChannel : PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JmgEmployeeAccuralRequestSvcClient : System.ServiceModel.ClientBase<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc>, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc {
        
        public JmgEmployeeAccuralRequestSvcClient() {
        }
        
        public JmgEmployeeAccuralRequestSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JmgEmployeeAccuralRequestSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JmgEmployeeAccuralRequestSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JmgEmployeeAccuralRequestSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.find(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find request) {
            return base.Channel.find(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog find(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, System.DateTime _profileDate, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._profileDate = _profileDate;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).find(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.findAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findResponse> findAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, System.DateTime _profileDate) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._profileDate = _profileDate;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.update(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update request) {
            return base.Channel.update(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog update(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).update(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.updateAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.updateResponse> updateAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retrieveAll(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll request) {
            return base.Channel.retrieveAll(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog retrieveAll(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll();
            inValue.CallContext = CallContext;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retrieveAll(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retrieveAllAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll request) {
            return base.Channel.retrieveAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAllResponse> retrieveAllAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retrieveAll();
            inValue.CallContext = CallContext;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retrieveAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.delete(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete request) {
            return base.Channel.delete(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog delete(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, long[] _recordsRecId, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).delete(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.deleteAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.deleteResponse> deleteAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, long[] _recordsRecId) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.create(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create request) {
            return base.Channel.create(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog create(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.GeneralContract result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).create(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.createAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.createResponse> createAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract contract) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.findByEmployee(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee request) {
            return base.Channel.findByEmployee(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog findByEmployee(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).findByEmployee(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.findByEmployeeAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee request) {
            return base.Channel.findByEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployeeResponse> findByEmployeeAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.findByEmployee();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).findByEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retriveEmployeeRequestioner(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner request) {
            return base.Channel.retriveEmployeeRequestioner(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog retriveEmployeeRequestioner(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retriveEmployeeRequestioner(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retriveEmployeeRequestionerAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner request) {
            return base.Channel.retriveEmployeeRequestionerAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestionerResponse> retriveEmployeeRequestionerAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeRequestioner();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retriveEmployeeRequestionerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retriveEmployeeReportees(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees request) {
            return base.Channel.retriveEmployeeReportees(request);
        }
        
        public PortalIntegration.JmgEmployeeAccuralRequestSvcReference.Infolog retriveEmployeeReportees(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType, out PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvcContract[] result) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse retVal = ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retriveEmployeeReportees(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse> PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc.retriveEmployeeReporteesAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees request) {
            return base.Channel.retriveEmployeeReporteesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReporteesResponse> retriveEmployeeReporteesAsync(PortalIntegration.JmgEmployeeAccuralRequestSvcReference.CallContext CallContext, string _employeeId, PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgAccuralRequestType _requestType) {
            PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees inValue = new PortalIntegration.JmgEmployeeAccuralRequestSvcReference.retriveEmployeeReportees();
            inValue.CallContext = CallContext;
            inValue._employeeId = _employeeId;
            inValue._requestType = _requestType;
            return ((PortalIntegration.JmgEmployeeAccuralRequestSvcReference.JmgEmployeeAccuralRequestSvc)(this)).retriveEmployeeReporteesAsync(inValue);
        }
    }
}
