//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalIntegration.HRHiringRequisitionDetailsSvcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.HRHiringRequisitionDetailsSvcReference.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.HRHiringRequisitionDetailsSvcReference.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HRHiringRequisition_DetailsSvcContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class HRHiringRequisition_DetailsSvcContract : PortalIntegration.HRHiringRequisitionDetailsSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalBeniftsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BudgetYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EstimatedMonthlySalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpectedHiringDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HRSerialNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalIntegration.HRHiringRequisitionDetailsSvcReference.MonthsOfYear MonthsOfYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PartitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VacanciesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalBenifts {
            get {
                return this.AdditionalBeniftsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalBeniftsField, value) != true)) {
                    this.AdditionalBeniftsField = value;
                    this.RaisePropertyChanged("AdditionalBenifts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BudgetYear {
            get {
                return this.BudgetYearField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetYearField, value) != true)) {
                    this.BudgetYearField = value;
                    this.RaisePropertyChanged("BudgetYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAreaId {
            get {
                return this.DataAreaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAreaIdField, value) != true)) {
                    this.DataAreaIdField = value;
                    this.RaisePropertyChanged("DataAreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EstimatedMonthlySalary {
            get {
                return this.EstimatedMonthlySalaryField;
            }
            set {
                if ((this.EstimatedMonthlySalaryField.Equals(value) != true)) {
                    this.EstimatedMonthlySalaryField = value;
                    this.RaisePropertyChanged("EstimatedMonthlySalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpectedHiringDate {
            get {
                return this.ExpectedHiringDateField;
            }
            set {
                if ((this.ExpectedHiringDateField.Equals(value) != true)) {
                    this.ExpectedHiringDateField = value;
                    this.RaisePropertyChanged("ExpectedHiringDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExperienceField, value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HRSerialNumber {
            get {
                return this.HRSerialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.HRSerialNumberField, value) != true)) {
                    this.HRSerialNumberField = value;
                    this.RaisePropertyChanged("HRSerialNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobDescription {
            get {
                return this.JobDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.JobDescriptionField, value) != true)) {
                    this.JobDescriptionField = value;
                    this.RaisePropertyChanged("JobDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedByField, value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDateTime {
            get {
                return this.ModifiedDateTimeField;
            }
            set {
                if ((this.ModifiedDateTimeField.Equals(value) != true)) {
                    this.ModifiedDateTimeField = value;
                    this.RaisePropertyChanged("ModifiedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.MonthsOfYear MonthsOfYear {
            get {
                return this.MonthsOfYearField;
            }
            set {
                if ((this.MonthsOfYearField.Equals(value) != true)) {
                    this.MonthsOfYearField = value;
                    this.RaisePropertyChanged("MonthsOfYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Partition {
            get {
                return this.PartitionField;
            }
            set {
                if ((this.PartitionField.Equals(value) != true)) {
                    this.PartitionField = value;
                    this.RaisePropertyChanged("Partition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Vacancies {
            get {
                return this.VacanciesField;
            }
            set {
                if ((this.VacanciesField.Equals(value) != true)) {
                    this.VacanciesField = value;
                    this.RaisePropertyChanged("Vacancies");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract))]
    public partial class XppObjectBase : PortalIntegration.HRHiringRequisitionDetailsSvcReference.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class GeneralContract : PortalIntegration.HRHiringRequisitionDetailsSvcReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonthsOfYear", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum MonthsOfYear : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        January = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        February = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        March = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        April = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        May = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        June = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        July = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        August = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        September = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        October = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        November = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        December = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc")]
    public interface HRHiringRequisition_DetailsSvc {
        
        // CODEGEN: Generating message contract since message find has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/find", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/findResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Fault), Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse find(PortalIntegration.HRHiringRequisitionDetailsSvcReference.find request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/find", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/findResponse")]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse> findAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.find request);
        
        // CODEGEN: Generating message contract since message update has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/update", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/updateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Fault), Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse update(PortalIntegration.HRHiringRequisitionDetailsSvcReference.update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/update", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/updateResponse")]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse> updateAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.update request);
        
        // CODEGEN: Generating message contract since message delete has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/delete", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Fault), Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse delete(PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/delete", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/deleteResponse")]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse> deleteAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete request);
        
        // CODEGEN: Generating message contract since message create has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/create", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/createResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Fault), Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse create(PortalIntegration.HRHiringRequisitionDetailsSvcReference.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HRHiringRequisition_DetailsSvc/create", ReplyAction="http://tempuri.org/HRHiringRequisition_DetailsSvc/createResponse")]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse> createAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.create request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class find {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _serialNumber;
        
        public find() {
        }
        
        public find(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, string _serialNumber) {
            this.CallContext = CallContext;
            this._serialNumber = _serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class findResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract[] result;
        
        public findResponse() {
        }
        
        public findResponse(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class update {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract;
        
        public update() {
        }
        
        public update(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result;
        
        public updateResponse() {
        }
        
        public updateResponse(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog, PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long[] _recordsRecId;
        
        public delete() {
        }
        
        public delete(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, long[] _recordsRecId) {
            this.CallContext = CallContext;
            this._recordsRecId = _recordsRecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract[] result;
        
        public deleteResponse() {
        }
        
        public deleteResponse(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog, PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class create {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract;
        
        public create() {
        }
        
        public create(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract) {
            this.CallContext = CallContext;
            this.contract = contract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result;
        
        public createResponse() {
        }
        
        public createResponse(PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog Infolog, PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HRHiringRequisition_DetailsSvcChannel : PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HRHiringRequisition_DetailsSvcClient : System.ServiceModel.ClientBase<PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc>, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc {
        
        public HRHiringRequisition_DetailsSvcClient() {
        }
        
        public HRHiringRequisition_DetailsSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HRHiringRequisition_DetailsSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRHiringRequisition_DetailsSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HRHiringRequisition_DetailsSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.find(PortalIntegration.HRHiringRequisitionDetailsSvcReference.find request) {
            return base.Channel.find(request);
        }
        
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog find(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, string _serialNumber, out PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract[] result) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.find inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._serialNumber = _serialNumber;
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse retVal = ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).find(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse> PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.findAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.find request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.findResponse> findAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, string _serialNumber) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.find inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.find();
            inValue.CallContext = CallContext;
            inValue._serialNumber = _serialNumber;
            return ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.update(PortalIntegration.HRHiringRequisitionDetailsSvcReference.update request) {
            return base.Channel.update(request);
        }
        
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog update(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract, out PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.update inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse retVal = ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).update(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse> PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.updateAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.update request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.updateResponse> updateAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.update inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.update();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.delete(PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete request) {
            return base.Channel.delete(request);
        }
        
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog delete(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, long[] _recordsRecId, out PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract[] result) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse retVal = ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).delete(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse> PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.deleteAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete request) {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.deleteResponse> deleteAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, long[] _recordsRecId) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.delete();
            inValue.CallContext = CallContext;
            inValue._recordsRecId = _recordsRecId;
            return ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.create(PortalIntegration.HRHiringRequisitionDetailsSvcReference.create request) {
            return base.Channel.create(request);
        }
        
        public PortalIntegration.HRHiringRequisitionDetailsSvcReference.Infolog create(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract, out PortalIntegration.HRHiringRequisitionDetailsSvcReference.GeneralContract result) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.create inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse retVal = ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).create(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse> PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc.createAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.create request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<PortalIntegration.HRHiringRequisitionDetailsSvcReference.createResponse> createAsync(PortalIntegration.HRHiringRequisitionDetailsSvcReference.CallContext CallContext, PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvcContract contract) {
            PortalIntegration.HRHiringRequisitionDetailsSvcReference.create inValue = new PortalIntegration.HRHiringRequisitionDetailsSvcReference.create();
            inValue.CallContext = CallContext;
            inValue.contract = contract;
            return ((PortalIntegration.HRHiringRequisitionDetailsSvcReference.HRHiringRequisition_DetailsSvc)(this)).createAsync(inValue);
        }
    }
}
